spring:
  application:
    name: hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
turbine:
  appConfig: application-service
  clusterNameExpression: "'default'"